apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    app: rabbitmq
    project: roboshop
    tier: db
spec:
  ports:
  - protocol: TCP
    port: 15672 #service-port
    targetPort: 15672
  clusterIP: None
  selector:
    app: rabbitmq
    project: roboshop
    tier: db